#!/bin/bash

localectl set-locale LANG=en_US.utf8

timedatectl set-ntp 1

xrdb ~/.Xresources && xrdb -merge \
	~/.Xresources.colors/`cat ~/.colorscheme`/`cat ~/.background`

export XAUTHORITY=~/.Xauthority
export DISPLAY=${DISPLAY:-:0.0}

xset b off && xset s off
xset r rate 130 80

setxkbmap -layout "us, ru" -option "grp:caps_toggle"
setxkbmap \
	-keycodes \
	"evdev+aliases(qwerty)+disable-arrows" \
	-symbols \
	"pc+us+ru:2+hjkl-ru+level3(lwin_switch)+mod4-lvl3+terminate(ctrl_alt_bksp)+capslock-groupshift" \
	-compat \
	"complete+hjkl"

xrandr --output HDMI-0 --mode 1920x1080 --right-of eDP --output eDP --off
