#!/bin/bash

xrdb ~/.Xresources && xrdb -merge ~/.Xresources.dark
xset b off && xset s off
xset r rate 130 27
setxkbmap -layout "us, ru" -option "grp:caps_toggle"

if [[ home = `hostname` ]]; then
	xrandr --output HDMI-0 --right-of LVDS-0
else
	xrandr --auto
fi
