alias ps="sudo pacman -S --noconfirm"
alias psy="ps -y"
alias psyy="psy -y"
alias psys="psy -s"
alias psyu="psy -u"
alias psu="ps -u"
alias pss="ps -s"

alias pq="pacman -Q"
alias pqs="pq -s"
alias pqi="pq -i"
alias pql="pq -l"
alias pqo="pq -o"

alias pr="sudo pacman -R"
alias pu="sudo pacman -U"
