alias am=alsamixer
alias bt="acpi"
alias psa="/bin/ps auxf"
alias rr="rm -rf"
alias pwgen="pwgen 12 -y"
alias me="mysql uveliria-idfly-ru -e"
alias ym="./yii migrate"
alias pgrep="pgrep -f -a"
alias pkill="pkill -f"
alias ardour="ardour4"
alias task="python /usr/lib/python3.4/site-packages/t.py --task-dir ~/.tasks --list tasks"
alias t="translator"
alias kill9="kill -9"
alias i="issue"
alias m="mplayer -zoom"
alias rto='rtorrent "$(/usr/bin/ls --color=never -t ~/Downloads/*.torrent | head -n1)"'
alias ag="ag --hidden"
alias ipa="ip a"
alias pb="pkgbuilds"
alias e="execute-on-hosts"
alias sz="source ~/.zshrc"
alias A="alias"
alias pks="pkgfile -s"
alias bpr="bitbucket pull-request"
alias bg="bash get"
alias ss="sed-replace"
alias ls='/usr/bin/ls --color --classify'
alias la='/usr/bin/ls --almost-all --color --classify'
alias ll='/usr/bin/ls -lA --color --human-readable -p'
alias lt='/usr/bin/ls -ltA --color --human-readable -p'
