#!/bin/bash

threshold_warning=15

threshold_force_suspend=5

sleep_interval=1m

while true; do
	stats=$(acpi)

	if [[ $stats == *"Charging"* ]]; then
		sleep_interval=1m
		sleep $sleep_interval
		continue
	fi

	if [[ $stats == *"Full"* ]]; then
		i3-nagbar -t warning -m \
			"Battery is full"
	fi

	percentage_current=$(
		echo $stats | \
		awk 'match($4, /[[:digit:]]+/) { print substr($4, RSTART, RLENGTH) }'
	)

	if [[ $percentage_current -le $threshold_warning ]]; then

		i3-nagbar -t warning -m \
			"Battery level is low ($percentage_current%)" \
			-b "Suspend" "sudo systemctl suspend"

		if [[ $percentage_current -le $threshold_force_suspend ]]; then
			sleep_interval=5s
			sudo systemctl suspend
		fi
	fi

	sleep $sleep_interval
done
