#!/bin/bash

# ~/.wine/drive_c/handhistory -> /zstorage/data/poker/handhistory

sudo -upostgres postgres -D /zstorage/data/poker/postgresql &

wine ~/.wine/drive_c/Program\ Files/PokerTracker\ 4/PokerTracker4.exe
