#!/bin/bash

localectl set-locale LANG=en_US.utf8

timedatectl set-ntp 1

xrdb ~/.Xresources && xrdb -merge \
	~/.Xresources.colors/`cat ~/.colorscheme`/`cat ~/.background`

export XAUTHORITY=~/.Xauthority
export DISPLAY=${DISPLAY:-:0.0}
export XDG_CONFIG_HOME=~/.xkb

xkbcomp $XDG_CONFIG_HOME/config $DISPLAY 2> /dev/null

xset b off && xset s off
xset r rate 120 100

redshift -l55.2:82.55 -o >/dev/null

pkill keynav; keynav 2>&1 >/dev/null
